### ISSUE TITLE
ValueError: Input tensors to a Functional must come from `tf.keras.Input`

### ISSUE THREAD

**Issue by onkar-99** [Abishalini/LipReadingGUI#2]
Hello. I get this error while running the GUI.py. Kindly let me know how to solve this. Thankyou

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\pedne\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\pedne\Desktop\onkar\Upwork\LipReadingGUI-master\PredictGUI\GUI.py", line 50, in caption
    video, result = predict(WEIGHTS_PATH, VIDEO_PATH)
  File "C:\Users\pedne\Desktop\onkar\Upwork\LipReadingGUI-master\PredictGUI\predict.py", line 59, in predict
    y_pred         = lipnet.predict(X_data)
  File "C:\Users\pedne\Desktop\onkar\Upwork\LipReadingGUI-master\PredictGUI\..\Training\lipnet\model.py", line 74, in predict
    return self.test_function([input_batch])[0]  # the first 0 indicates test
  File "C:\Users\pedne\Desktop\onkar\Upwork\LipReadingGUI-master\PredictGUI\..\Training\lipnet\model.py", line 79, in test_function
    return K.function([self.input_data, K.learning_phase()], [self.y_pred, K.learning_phase()])
  File "C:\Users\pedne\anaconda3\lib\site-packages\keras\backend.py", line 4062, in function
    model = models.Model(inputs=inputs, outputs=outputs)
  File "C:\Users\pedne\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\pedne\anaconda3\lib\site-packages\keras\engine\functional.py", line 110, in __init__
    self._init_graph_network(inputs, outputs)
  File "C:\Users\pedne\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\pedne\anaconda3\lib\site-packages\keras\engine\functional.py", line 147, in _init_graph_network
    self._validate_graph_inputs_and_outputs()
  File "C:\Users\pedne\anaconda3\lib\site-packages\keras\engine\functional.py", line 683, in _validate_graph_inputs_and_outputs
    raise ValueError('Input tensors to a ' + cls_name + ' ' +
ValueError: Input tensors to a Functional must come from `tf.keras.Input`. Received: 0 (missing previous layer metadata).

**Comment by Mr-Usama** [comment]
- just uninstall your tensorflow
-  and

- install this by 
- pip install tf-nightly (:
